### ISSUE TITLE
ToHitThisActor effects applied through debuff missing

### ISSUE THREAD

**Issue by LadyAlekto** [Sheep-y/Attack-Improvement-Mod#12]
I pinged you in discord but assume youre busy so i open an issue for you

Applying a ToHitThisActor to an enemy through a onhit status effect do not trigger anymore

**Comment by LadyAlekto** [comment]
In rt the mods are on the tag, tagger, narc and death stare

I got 3 reports of it missing (including 1 myself stacking all 4 effects)

I will now try to confirm through logs this is or isnt the issue

I hope i just missed something

**Comment by LadyAlekto** [comment]
BTw this seems to be fixed with 1.2.1 ne way to act with debuffs

**Comment by Sheep-y** [comment]
Ok, I'll close this for now then. Thanks for the update.
