### ISSUE TITLE
Jumping gives a +3 to-Hit penalty that lasts 2 rounds

### ISSUE THREAD

**Issue by Outis73** [Sheep-y/Attack-Improvement-Mod#17]
After jumping, a +3 to-Hit penalty is applied that last for 2 rounds if you stay stationary after jumping.

If you move the next round after jumping, only the normal movement penalties are applied.

**Comment by Sheep-y** [comment]
A preview release is out two days ago that contains the jump modifier fix, please check:

https://github.com/Sheep-y/Attack-Improvement-Mod/releases
