### ISSUE TITLE
CalledShotUseClustering no longer works (1.3.2)

### ISSUE THREAD

**Issue by talchas** [Sheep-y/Attack-Improvement-Mod#28]
It looks like the boss head bug has been partially fixed by the base game by copying the dictionary in the `GetHitLocation(Vector3 attackPosition, Mech target, ...)` method. This causes your `PrefixMechCalledShot` to fail to match any of the hit tables and do nothing.

I've fixed this personally by tracking if you are currently in `GetHitLocation(Vector,Mech)` and saving the direction from GetMechHitTable, I couldn't figure out a less hassle way of fixing this besides replacing GHL entirely.

(I suspect that boss heads are now only really broken in base in that you can try to called shot them and see 0% go to 0%, but I don't have a save handy)

**Comment by Sheep-y** [comment]
Thanks for the report!  Issue confirmed, both cause and effect.  Solution is sound too.  Will be fixed in next version, due soon.

**Comment by talchas** [comment]
Hmm, with that patch I'd worry about it affecting other callers of `GHL<ArmorLocation>`, using a left over essentially random direction. GetAdjacentHitLocation could (if anything uses it? At a minimum I think some mods do?), but is probably always followup to GHL and would be fine. Beyond that my look through calls only shows debug stuff, so it's probably actually fine enough, but still.

**Comment by Sheep-y** [comment]
Yes I agree. Added a cleanup which I think should prevent that, just to be safe, now released in 3.1. Thanks for the report and the advices.
