### ISSUE TITLE
Cursor locked up with redrawing LOS lines enabled

### ISSUE THREAD

**Issue by LadyAlekto** [Sheep-y/Attack-Improvement-Mod#29]
![20181213091106_1](https://user-images.githubusercontent.com/39632036/49924915-c0af8a00-feb7-11e8-9b4f-d55b67d83c2b.jpg)
![20181213091127_1](https://user-images.githubusercontent.com/39632036/49924918-c4dba780-feb7-11e8-99f1-f3b0bff1efb3.jpg)

Locks up moving the cursor as soon as a firing line is drawn

This seems to fix it 

  /* Range and speed (in half-cycle ms) of firing line animation. */

  "LOSHueDeviation": 0,
  "LOSHueHalfCycleMS": 0,
  "LOSBrightnessDeviation": 0,
  "LOSBrightnessHalfCycleMS": 0,

**Comment by Sheep-y** [comment]
Should be fixed in [3.1](https://github.com/Sheep-y/Attack-Improvement-Mod/releases/tag/v3.1).
