### ISSUE TITLE
question - are you looking for contributions?  I like this mod idea!

### ISSUE THREAD

**Issue by gnivler** [Sheep-y/Attack-Improvement-Mod#3]

**Comment by Sheep-y** [comment]
I don't mind suggest, insight, or merge request (code contrib.).  I think mine is one of the few mods on nexusmod that does not exclude people from taking it and play with its code.

I am working on this feature list, roughly in the order described:

https://github.com/Sheep-y/BattleTech_Mods/issues/2

You can also suggest features by commenting there.

**Comment by gnivler** [comment]
Appreciated, I will take a read through code/list and see if anything is in my range.

**Comment by Sheep-y** [comment]
I've marked the list as help wanted so I'm closing this issue now. Thanks for the interest!
