### ISSUE TITLE
A toggle to have melee be affected by evasive

### ISSUE THREAD

**Issue by LadyAlekto** [Sheep-y/Attack-Improvement-Mod#7]
Sooo after raz helped me fix AIM (or rather fixed the initpoint) (love toying with the returns settings, gonna keep me busy;))

I continued on finding how to have melee be affected by evasive

What i have found, is that the melee calculations just leave out the 		

	float targetSpeedModifier = this.GetTargetSpeedModifier(target, weapon);

in the 

       public float GetAllMeleeModifiers(Mech attacker, ICombatant target, Vector3 targetPosition, MeleeAttackType meleeAttackType)

Would it be possible or is it just a stupid idea of mine?

(and if this works, how hard would it be to add the other modifiers that arent entirely gun related into these calculations? public float GetAllModifiers)

Oh yeah so i dont forget it, even though ia ssume you probably know it, its all in Battletech.ToHit

**Comment by Sheep-y** [comment]
Interesting.  Yes melee and evasion should be handled in that function.  Can implement "melee ignores X pips" or "melee ignores X%" or, yes, do that to laser or energy too.

These are changes that I prefer to be modified in json, but I would admit that my mod has the advantage of not corrupting saves and may persist over game updates.  What do you have in mind?

**Comment by LadyAlekto** [comment]
Melee already ignores any and all evasion

I want it to not not do that anymore, basically have it be affected by the GetTargetSpeedModifier function too

And since your mod is the aim mod, i thought it would make sense

**Comment by LadyAlekto** [comment]
this is the tohit for normal weapons

public float GetAllModifiers(AbstractActor attacker, Weapon weapon, ICombatant target, Vector3 attackPosition, Vector3 targetPosition, LineOfFireLevel lofLevel, bool isCalledShot)
		{
			bool flag = lofLevel < LineOfFireLevel.LOFObstructed && weapon.IndirectFireCapable;
			float rangeModifier = this.GetRangeModifier(weapon, attackPosition, targetPosition);
			float coverModifier = this.GetCoverModifier(attacker, target, lofLevel);
			float selfSpeedModifier = this.GetSelfSpeedModifier(attacker);
			float selfSprintedModifier = this.GetSelfSprintedModifier(attacker);
			float selfArmMountedModifier = this.GetSelfArmMountedModifier(weapon);
			float stoodUpModifier = this.GetStoodUpModifier(attacker);
			float heightModifier = this.GetHeightModifier(attackPosition.y, targetPosition.y);
			float heatModifier = this.GetHeatModifier(attacker);
			float targetTerrainModifier = this.GetTargetTerrainModifier(target, targetPosition, false);
			float selfTerrainModifier = this.GetSelfTerrainModifier(attackPosition, false);
			float targetSpeedModifier = this.GetTargetSpeedModifier(target, weapon);
			float selfDamageModifier = this.GetSelfDamageModifier(attacker, weapon);
			float targetSizeModifier = this.GetTargetSizeModifier(target);
			float targetShutdownModifier = this.GetTargetShutdownModifier(target, false);
			float targetProneModifier = this.GetTargetProneModifier(target, false);
			float weaponAccuracyModifier = this.GetWeaponAccuracyModifier(attacker, weapon);
			float attackerAccuracyModifier = this.GetAttackerAccuracyModifier(attacker);
			float enemyEffectModifier = this.GetEnemyEffectModifier(target);
			float refireModifier = this.GetRefireModifier(weapon);
			float targetDirectFireModifier = this.GetTargetDirectFireModifier(target, flag);
			float indirectModifier = this.GetIndirectModifier(attacker, flag);
			float moraleAttackModifier = this.GetMoraleAttackModifier(target, isCalledShot);
			float num = rangeModifier + coverModifier + selfSpeedModifier + selfSprintedModifier + selfArmMountedModifier + stoodUpModifier + heightModifier + heatModifier + targetTerrainModifier + selfTerrainModifier + targetSpeedModifier + selfDamageModifier + targetSizeModifier + targetShutdownModifier + targetProneModifier + weaponAccuracyModifier + attackerAccuracyModifier + enemyEffectModifier + refireModifier + targetDirectFireModifier + indirectModifier + moraleAttackModifier;
			if (num < 0f && !this.combat.Constants.ResolutionConstants.AllowTotalNegativeModifier)
			{
				num = 0f;
			}
			return num;
		}


this is the MeleeToHIt, lacking several modifiers

		public float GetAllMeleeModifiers(Mech attacker, ICombatant target, Vector3 targetPosition, MeleeAttackType meleeAttackType)
		{
			Weapon weapon;
			if (meleeAttackType == MeleeAttackType.DFA)
			{
				weapon = attacker.DFAWeapon;
			}
			else
			{
				weapon = attacker.MeleeWeapon;
			}
			float selfSpeedModifier = this.GetSelfSpeedModifier(attacker);
			float heatModifier = this.GetHeatModifier(attacker);
			float targetSizeModifier = this.GetTargetSizeModifier(target);
			float targetShutdownModifier = this.GetTargetShutdownModifier(target, true);
			float targetProneModifier = this.GetTargetProneModifier(target, true);
			float targetTerrainModifier = this.GetTargetTerrainModifier(target, targetPosition, true);
			float enemyEffectModifier = this.GetEnemyEffectModifier(target);
			float meleeChassisToHitModifier = this.GetMeleeChassisToHitModifier(attacker, meleeAttackType);
			float weaponAccuracyModifier = this.GetWeaponAccuracyModifier(attacker, weapon);
			float dfamodifier = this.GetDFAModifier(meleeAttackType);
			float num = selfSpeedModifier + heatModifier + targetSizeModifier + targetShutdownModifier + targetProneModifier + targetTerrainModifier + enemyEffectModifier + meleeChassisToHitModifier + weaponAccuracyModifier + dfamodifier;
			if (num < 0f && !this.combat.Constants.ResolutionConstants.AllowTotalNegativeModifier)
			{
				num = 0f;
			}
			return num;
		}

**Comment by Sheep-y** [comment]
Melee evasion is not hard to do.  Applying other gun modifiers is more generic and doesn't translate well to code.  Will need to dig into each modifier function to give a better evaulation.

**Comment by LadyAlekto** [comment]
The list of what id say could best work to be added to melee

  selfSprintedModifier 
  stoodUpModifier 
  selfTerrainModifier 
  
Basically all these which arent directly tied to a weapon but the attacker/defender

**Comment by Sheep-y** [comment]
Self note: `CombatHUDWeaponSlot.UpdateToolTipsMelee` also need to be patched to show the correct modifier list.

**Comment by LadyAlekto** [comment]
TIL

**Comment by LadyAlekto** [comment]
Thats how ive been the last month everytime ive been looking at what i can do with statuseffects

theres so much stuff it uses and then not uses :/

**Comment by Sheep-y** [comment]
It's generally a good thing.  The more things it leave in code, the more things we can reuse and generally speaking the more flexible the code is.

Published a new preview that restore evasion to melee by default.  Note that melee weapon ignores up to 4 evasion pips by default, so it only matters against very fast enemies who somehow moved that far.

**Comment by LadyAlekto** [comment]
which is very not unusual in RT and i already removed that from melee

**Comment by LadyAlekto** [comment]
![20180712045643_1](https://user-images.githubusercontent.com/39632036/42610435-e3c01c66-8591-11e8-9c99-9ed8fb9c7145.jpg)

**Comment by LadyAlekto** [comment]
Didnt quit work out as it seems :/

**Comment by LadyAlekto** [comment]
Disregard anything im an idot -.-

always doublechek your own files....

**Comment by Sheep-y** [comment]
The preview release misspelled "obstructed" and has been fixed.  I also checked range modifiers, there is a minor bug that affects display of a bonus but nothing is missing like melee.  So, 2.1 may be.
